name: thunder_cloud_app
description: "積乱雲検出・通知アプリ - リアルタイムで積乱雲を監視し、危険を事前に察知"
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1

  cupertino_icons: ^1.0.8
  http: ^1.2.2

  #背景に現在地を表示するためのパッケージ
  geolocator: ^13.0.4
  google_maps_flutter: ^2.5.0

  #通知機能を実装するためのパッケージ
  flutter_local_notifications: ^19.2.1

  #Firebase依存関係を追加
  firebase_core: ^3.13.1
  firebase_messaging: ^15.2.6
  firebase_analytics: ^11.4.6
  cloud_firestore: ^5.6.8
  cloud_functions: ^5.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - image/transparent.jpg
    - image/direction.png
    - image/bluesky.jpg
    - image/cloud2.jpg
    - assets/images/thunder_cloud.png
