name: thunder_cloud_app
description: "入道雲サーチアプリ - 美しい入道雲の発生を検出・通知する観賞・撮影支援アプリ"
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2

  #背景に現在地を表示するためのパッケージ
  geolocator: ^13.0.4
  google_maps_flutter: ^2.5.0

  #通知機能を実装するためのパッケージ
  flutter_local_notifications: ^19.2.1

  #Firebase依存関係を追加
  firebase_core: ^3.13.1
  firebase_messaging: ^15.2.6
  firebase_analytics: ^11.4.6
  cloud_firestore: ^5.6.8
  cloud_functions: ^5.5.1
  firebase_storage: ^12.0.1

  # カメラ・画像機能
  camera: ^0.11.1
  image_picker: ^1.1.2
  image: ^4.5.4
  path_provider: ^2.1.5
  permission_handler: ^12.0.0

  # UI強化
  cached_network_image: ^3.4.1
  photo_view: ^0.15.0
  share_plus: ^11.0.0
  image_gallery_saver: ^2.0.3
  photo_manager: ^3.5.0

  # ローカルキャッシュ機能
  shared_preferences: ^2.5.3

  # UUID生成
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - image/transparent.jpg
    - image/direction.png
    - image/bluesky.jpg
    - image/cloud2.jpg
    - assets/images/
