// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZP8nwDl8FDXVvtYpF_b_REQbwsVpnZ2E',
    appId: '1:852675497714:android:cb7c8922121301a8334a6b',
    messagingSenderId: '852675497714',
    projectId: 'thunder-cloud-app-292e6',
    storageBucket: 'thunder-cloud-app-292e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8q8kr1HYOMNpDPZQ-Mp4UQ6zIzbmGjUw',
    appId: '1:852675497714:ios:df6d20b3d0372f06334a6b',
    messagingSenderId: '852675497714',
    projectId: 'thunder-cloud-app-292e6',
    storageBucket: 'thunder-cloud-app-292e6.firebasestorage.app',
    iosBundleId: 'com.tsuchida.thundercloud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8q8kr1HYOMNpDPZQ-Mp4UQ6zIzbmGjUw',
    appId: '1:852675497714:ios:6f1cd34095293552334a6b',
    messagingSenderId: '852675497714',
    projectId: 'thunder-cloud-app-292e6',
    storageBucket: 'thunder-cloud-app-292e6.firebasestorage.app',
    iosBundleId: 'com.example.thunderCloudApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXLoqfiz33_IU4ub83a9MEnS1MbN57TY4',
    appId: '1:852675497714:web:e1a695f21b74f582334a6b',
    messagingSenderId: '852675497714',
    projectId: 'thunder-cloud-app-292e6',
    authDomain: 'thunder-cloud-app-292e6.firebaseapp.com',
    storageBucket: 'thunder-cloud-app-292e6.firebasestorage.app',
    measurementId: 'G-CQFBJZ7T40',
  );

}